import React from 'react';

import Head from 'next/head';

import About from '@/Components/About';
import Footer from '@/Components/Footer';
import Header from '@/Components/Header';
import Resume from '@/Components/Resume';
import Works from '@/Components/Works';

const Home = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>Brian&apos;s Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/brianIcon.ico" />
      </Head>

      <Header />
      <main className="pt-[5%]">
        <About />
        <Resume />
        <Works />
      </main>
      <Footer />
    </>
  );
};

export default Home;
